---
  - name: Install hbs 
    unarchive: src=hbs.tar.gz dest={{ INSTALL_PATH }}/hbs 

  - name: Config Service
    template: 
      src=systemd.service.j2 
      dest=/usr/lib/systemd/system/openfalcon-hbs.service
      group=root
      owner=root
      mode=0644

  - name: Config hbs
    template: src=cfg.json.j2 dest={{ INSTALL_PATH }}/hbs/cfg.json

  - name: system reload
    shell: "systemctl daemon-reload"

  - name: Start service
    service: name=openfalcon-hbs.service  state=restarted  enabled=yes
