---
  - name: Install graph 
    unarchive: src=graph.tar.gz dest={{ INSTALL_PATH }}  creates={{ INSTALL_PATH }}/graph

  - name: Config Service
    template: 
      src=systemd.service.j2 
      dest=/usr/lib/systemd/system/openfalcon-graph.service
      group=root
      owner=root
      mode=0644

  - name: Config graph
    template: src=cfg.json.j2 dest={{ INSTALL_PATH }}/graph/cfg.json

  - name: system reload
    shell: "systemctl daemon-reload"

  - name: Start service
    service: name=openfalcon-graph.service  state=restarted  enabled=yes
