---
  - name: config proxy .env
    template: src=env.j2 dest={{ proxy.magicstack_proxy_path }}/.env
 
  - name: config proxy flask service
    template: src=magicstack-proxy-flask.service.j2 dest=/usr/lib/systemd/system/magicstack-proxy-flask.service
    #notify: start proxys.service
